version: '3'

services:
  corridor-django:
    build:
      context: ./
    command: python3 src/manage.py runserver 0.0.0.0:8001
    container_name: 'corridor-django'
    labels:
      application: 'corridor-django'
    volumes:
      - ./:/code
    ports:
      - '8001:8001'
    expose:
      - '8001'
    environment:
      DEBUG: 'True'
      SECRET_KEY: 'SECRET_KEY'
      REDIS_URL: 'redis://corridor-redis:6379'

  corridor-redis:
    image: redis:latest
    container_name: 'corridor-redis'
    labels:
      application: 'corridor-redis'
    ports:
      - '6379:6379'
    expose:
      - '6379'
